// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDeOrdenes.DAL;

namespace RegistroDeOrdenes.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211011202447_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("RegistroDeOrdenes.Entidades.Permisos", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoId = 1,
                            Descripcion = "Permiso para que el trabajador pueda estudiar",
                            Nombre = "Permiso para estudios"
                        },
                        new
                        {
                            PermisoId = 2,
                            Descripcion = "Permiso para que el trabajador descanse",
                            Nombre = "Permiso por Vacaiones"
                        },
                        new
                        {
                            PermisoId = 3,
                            Descripcion = "Permiso para que el trbajador salga en caso de emergencia",
                            Nombre = "Permiso de emergencia"
                        },
                        new
                        {
                            PermisoId = 4,
                            Descripcion = "Permiso para que el trabajador visite a medico en caso de enfermedad",
                            Nombre = "Permiso de salud"
                        });
                });

            modelBuilder.Entity("RegistroDeOrdenes.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("esActivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("RegistroDeOrdenes.Entidades.RolDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("esAsignado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("RolDetalle");
                });

            modelBuilder.Entity("RegistroDeOrdenes.Entidades.RolDetalle", b =>
                {
                    b.HasOne("RegistroDeOrdenes.Entidades.Rol", null)
                        .WithMany("RolDetalle")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroDeOrdenes.Entidades.Rol", b =>
                {
                    b.Navigation("RolDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
